#!/bin/bash

__HELP__="
   Bash multiple argments input reader example
   Parameters:
      help|--help|-h                Show this message
      foo1=bar1                     Get bar1 from variable foo1
      foo2                          Check if the foo2 was provided
      foo3 bar3                     Get bar3 for argument foo3
                                    Note: in this form, bar3 cannot be equal foo3. eg: $0 foo3 foo3

   Obs.: if any of this parameter is not given in the property, it will be prompt when script is running
   Examples.:
      $0 foo1=abc foo2 foo3 bar3
      $0 # This will show the help message as well
      $0 help
"

# Read parameters given in the script in the format xpto=abc
if [ $# -eq 0 ]; then echo "$__HELP__" ; exit 0 ; fi
__arguments__=("$@")
for i in "${!__arguments__[@]}"; do
   arg=${__arguments__[$i]}
   case $arg in
      -h | --help | help)
         echo "$__HELP__"
         exit 0;;
      foo1=*) foo1=${arg##*=};;
      foo2) foo2=$arg;;
      foo3) foo3=${__arguments__[$i+1]}
   esac
done

if [ ! -z $foo1 ]; then echo "The value for arg foo1 is $foo1"; fi
if [ ! -z $foo2 ]; then echo "Argument foo2 was provided"; fi
if [ ! -z $foo3 ]; then echo "Value of foo3 is $foo3"; fi
